#pragma once

#include "material_package.h"

#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_FORCE_RADIANS
#include <glm/glm.hpp>

#include <vulkan/vulkan.h>
#include <vk_mem_alloc.h>

#include <unordered_map>

namespace mat {

// Device-level state needed to build pipelines and descriptor layouts.
struct GpuContext {
    VkDevice              device;
    VmaAllocator          allocator;
    VkFormat              colorFormat;
    VkFormat              depthFormat;
    VkDescriptorSetLayout frameSetLayout; // set 0 — camera / lighting UBO
};

// Vertex layout consumed by material pipelines.
// Matches the attribute locations generated by codegen.cpp:
//   loc0 = position (vec3)
//   loc1 = normal   (vec3)
//   loc2 = tangent  (vec4, w = handedness)
//   loc3 = uv0      (vec2)
struct MaterialVertex {
    glm::vec3 pos;
    glm::vec3 normal;
    glm::vec4 tangent;
    glm::vec2 uv0;
};

// Owns all GPU resources derived from a MaterialPackage:
//   - VkDescriptorSetLayout for set 1 (param UBO at binding 0; samplers at bindings 1+)
//   - VkPipelineLayout combining frame set layout (set 0) and material set layout (set 1)
//   - Lazy VkPipeline cache keyed by variant key
//
// Created via Material::create(). Must be destroyed explicitly via destroy().
// Move-only; copying is deleted.
class Material {
public:
    static Material create(const MaterialPackage& pkg, const GpuContext& ctx);

    Material(Material&& o) noexcept;
    Material& operator=(Material&&) noexcept;
    Material(const Material&)       = delete;
    Material& operator=(const Material&) = delete;

    // Returns the pipeline for the given variant key, creating it on first call.
    // Returns VK_NULL_HANDLE if the variant was not compiled into the package.
    VkPipeline pipelineFor(uint32_t variantKey);

    VkDescriptorSetLayout  materialSetLayout() const { return materialSetLayout_; }
    VkPipelineLayout       pipelineLayout()    const { return pipelineLayout_; }
    const MaterialPackage& package()           const { return pkg_; }
    const GpuContext&      context()           const { return ctx_; }

    void destroy();

private:
    Material() = default;

    VkPipeline buildPipeline(const VariantDesc& variant) const;

    MaterialPackage       pkg_;
    GpuContext            ctx_{};
    VkDescriptorSetLayout materialSetLayout_ = VK_NULL_HANDLE;
    VkPipelineLayout      pipelineLayout_    = VK_NULL_HANDLE;
    std::unordered_map<uint32_t, VkPipeline> pipelineCache_;
};

} // namespace mat
